// Code generated by protoc-gen-go. DO NOT EDIT.
// source: variable.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Protocol buffer representing a Variable.
type VariableDef struct {
	// Name of the variable tensor.
	VariableName string `protobuf:"bytes,1,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	// Name of the tensor holding the variable's initial value.
	InitialValueName string `protobuf:"bytes,6,opt,name=initial_value_name,json=initialValueName,proto3" json:"initial_value_name,omitempty"`
	// Name of the initializer op.
	InitializerName string `protobuf:"bytes,2,opt,name=initializer_name,json=initializerName,proto3" json:"initializer_name,omitempty"`
	// Name of the snapshot tensor.
	SnapshotName string `protobuf:"bytes,3,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	// Support for saving variables as slices of a larger variable.
	SaveSliceInfoDef *SaveSliceInfoDef `protobuf:"bytes,4,opt,name=save_slice_info_def,json=saveSliceInfoDef,proto3" json:"save_slice_info_def,omitempty"`
	// Whether to represent this as a ResourceVariable.
	IsResource bool `protobuf:"varint,5,opt,name=is_resource,json=isResource,proto3" json:"is_resource,omitempty"`
	// Whether this variable should be trained.
	Trainable            bool     `protobuf:"varint,7,opt,name=trainable,proto3" json:"trainable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VariableDef) Reset()         { *m = VariableDef{} }
func (m *VariableDef) String() string { return proto.CompactTextString(m) }
func (*VariableDef) ProtoMessage()    {}
func (*VariableDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_444e051a4c91cdda, []int{0}
}

func (m *VariableDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableDef.Unmarshal(m, b)
}
func (m *VariableDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableDef.Marshal(b, m, deterministic)
}
func (m *VariableDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableDef.Merge(m, src)
}
func (m *VariableDef) XXX_Size() int {
	return xxx_messageInfo_VariableDef.Size(m)
}
func (m *VariableDef) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableDef.DiscardUnknown(m)
}

var xxx_messageInfo_VariableDef proto.InternalMessageInfo

func (m *VariableDef) GetVariableName() string {
	if m != nil {
		return m.VariableName
	}
	return ""
}

func (m *VariableDef) GetInitialValueName() string {
	if m != nil {
		return m.InitialValueName
	}
	return ""
}

func (m *VariableDef) GetInitializerName() string {
	if m != nil {
		return m.InitializerName
	}
	return ""
}

func (m *VariableDef) GetSnapshotName() string {
	if m != nil {
		return m.SnapshotName
	}
	return ""
}

func (m *VariableDef) GetSaveSliceInfoDef() *SaveSliceInfoDef {
	if m != nil {
		return m.SaveSliceInfoDef
	}
	return nil
}

func (m *VariableDef) GetIsResource() bool {
	if m != nil {
		return m.IsResource
	}
	return false
}

func (m *VariableDef) GetTrainable() bool {
	if m != nil {
		return m.Trainable
	}
	return false
}

type SaveSliceInfoDef struct {
	// Name of the full variable of which this is a slice.
	FullName string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// Shape of the full variable.
	FullShape []int64 `protobuf:"varint,2,rep,packed,name=full_shape,json=fullShape,proto3" json:"full_shape,omitempty"`
	// Offset of this variable into the full variable.
	VarOffset []int64 `protobuf:"varint,3,rep,packed,name=var_offset,json=varOffset,proto3" json:"var_offset,omitempty"`
	// Shape of this variable.
	VarShape             []int64  `protobuf:"varint,4,rep,packed,name=var_shape,json=varShape,proto3" json:"var_shape,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveSliceInfoDef) Reset()         { *m = SaveSliceInfoDef{} }
func (m *SaveSliceInfoDef) String() string { return proto.CompactTextString(m) }
func (*SaveSliceInfoDef) ProtoMessage()    {}
func (*SaveSliceInfoDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_444e051a4c91cdda, []int{1}
}

func (m *SaveSliceInfoDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveSliceInfoDef.Unmarshal(m, b)
}
func (m *SaveSliceInfoDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveSliceInfoDef.Marshal(b, m, deterministic)
}
func (m *SaveSliceInfoDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveSliceInfoDef.Merge(m, src)
}
func (m *SaveSliceInfoDef) XXX_Size() int {
	return xxx_messageInfo_SaveSliceInfoDef.Size(m)
}
func (m *SaveSliceInfoDef) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveSliceInfoDef.DiscardUnknown(m)
}

var xxx_messageInfo_SaveSliceInfoDef proto.InternalMessageInfo

func (m *SaveSliceInfoDef) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *SaveSliceInfoDef) GetFullShape() []int64 {
	if m != nil {
		return m.FullShape
	}
	return nil
}

func (m *SaveSliceInfoDef) GetVarOffset() []int64 {
	if m != nil {
		return m.VarOffset
	}
	return nil
}

func (m *SaveSliceInfoDef) GetVarShape() []int64 {
	if m != nil {
		return m.VarShape
	}
	return nil
}

func init() {
	proto.RegisterType((*VariableDef)(nil), "tensorflow.VariableDef")
	proto.RegisterType((*SaveSliceInfoDef)(nil), "tensorflow.SaveSliceInfoDef")
}

func init() { proto.RegisterFile("variable.proto", fileDescriptor_444e051a4c91cdda) }

var fileDescriptor_444e051a4c91cdda = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xc1, 0x6a, 0x2a, 0x31,
	0x14, 0x40, 0x89, 0xe3, 0xf3, 0xe9, 0xf5, 0xe9, 0x93, 0x79, 0x9b, 0x81, 0x67, 0xa9, 0xe8, 0x66,
	0x0a, 0xc5, 0x42, 0xfb, 0x07, 0xe2, 0xa6, 0x14, 0x5a, 0x19, 0xc1, 0xed, 0x70, 0xb5, 0x37, 0x35,
	0x34, 0x26, 0x92, 0x8c, 0x11, 0xfa, 0x09, 0xfd, 0xa6, 0x7e, 0x58, 0x97, 0x25, 0x99, 0x19, 0x14,
	0xb7, 0xe7, 0x9c, 0x4c, 0x26, 0x37, 0x81, 0xbe, 0x43, 0x23, 0x70, 0x2d, 0x69, 0xba, 0x37, 0xba,
	0xd0, 0x31, 0x14, 0xa4, 0xac, 0x36, 0x5c, 0xea, 0xe3, 0xf8, 0xab, 0x01, 0xdd, 0x55, 0xa5, 0xe7,
	0xc4, 0xe3, 0x09, 0xf4, 0xea, 0x3a, 0x57, 0xb8, 0xa3, 0x84, 0x8d, 0x58, 0xda, 0xc9, 0xfe, 0xd4,
	0xf0, 0x19, 0x77, 0x14, 0xdf, 0x42, 0x2c, 0x94, 0x28, 0x04, 0xca, 0xdc, 0xa1, 0x3c, 0x54, 0x65,
	0x2b, 0x94, 0x83, 0xca, 0xac, 0xbc, 0x08, 0xf5, 0x0d, 0xd4, 0x4c, 0x7c, 0x90, 0x29, 0xdb, 0x46,
	0x68, 0xff, 0x9e, 0xf1, 0x90, 0x4e, 0xa0, 0x67, 0x15, 0xee, 0xed, 0x56, 0x17, 0x65, 0x17, 0x95,
	0xbb, 0xd7, 0x30, 0x44, 0x4f, 0xf0, 0xcf, 0xa2, 0xa3, 0xdc, 0x4a, 0xb1, 0xa1, 0x5c, 0x28, 0xae,
	0xf3, 0x57, 0xe2, 0x49, 0x73, 0xc4, 0xd2, 0xee, 0xfd, 0x70, 0x7a, 0x3a, 0xdc, 0x74, 0x89, 0x8e,
	0x96, 0xbe, 0x7a, 0x54, 0x5c, 0xcf, 0x89, 0x67, 0x03, 0x7b, 0x41, 0xe2, 0x6b, 0xe8, 0x0a, 0x9b,
	0x1b, 0xb2, 0xfa, 0x60, 0x36, 0x94, 0xfc, 0x1a, 0xb1, 0xb4, 0x9d, 0x81, 0xb0, 0x59, 0x45, 0xe2,
	0x21, 0x74, 0x0a, 0x83, 0x42, 0xf9, 0xc3, 0x27, 0xbf, 0x83, 0x3e, 0x81, 0xf1, 0x27, 0x83, 0xc1,
	0xe5, 0x2e, 0xf1, 0x7f, 0xe8, 0xf0, 0x83, 0x94, 0xe7, 0xf3, 0x6b, 0x7b, 0x10, 0xfe, 0xfe, 0x0a,
	0x20, 0x48, 0xbb, 0xc5, 0xbd, 0x9f, 0x43, 0x94, 0x46, 0x59, 0xc8, 0x97, 0x1e, 0x78, 0xed, 0xd0,
	0xe4, 0x9a, 0x73, 0x4b, 0x45, 0x12, 0x95, 0xda, 0xa1, 0x79, 0x09, 0xc0, 0x7f, 0xda, 0xeb, 0x72,
	0x71, 0x33, 0xd8, 0xb6, 0x43, 0x13, 0xd6, 0xce, 0xee, 0x20, 0xd1, 0xe6, 0xed, 0x7c, 0x00, 0xdc,
	0xe0, 0x8e, 0x8e, 0xda, 0xbc, 0xcf, 0xfa, 0xf5, 0x25, 0x2f, 0xfc, 0x13, 0xb0, 0x0b, 0xf6, 0xcd,
	0xd8, 0xba, 0x15, 0xde, 0xc3, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xdd, 0x60, 0x74,
	0x21, 0x02, 0x00, 0x00,
}
